# Generated by Django 3.1.12 on 2021-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpe',
            name='course_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
